apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: webapp
spec:
  selector:
      matchLabels:
        app: web
  replicas: 1
  template:
      metadata:
        labels:
            app: web
      spec:
        containers:
        - name: web
          image:  khanasif1/k8_web:rc0
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"          
          readinessProbe:
            httpGet:
              port: 80
              path: /healthcheck
          livenessProbe:
            httpGet:
              port: 80
              path: /healthcheck
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: webapp
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP      